#!/bin/bash


#ROOT='./'

#--------------------------------------------------------------------
echo "Deploy started at: " + $(date)

#cd $ROOT

# echo "Running: git pull" + $(date)
#git pull

#echo "Running: composer install" + $(date)
composer update

echo "Clear cache and generated content" + $(date)
rm -rf $ROOT/pub/static/* $ROOT/var/cache/* $ROOT/var/page_cache/* $ROOT/var/view_preprocessed/* $ROOT/generated/code/* $ROOT/generated/metadata/*

echo "Running: setup:upgrade" + $(date)
bin/magento setup:upgrade

echo "Running: di:compile" + $(date)
bin/magento setup:di:compile

echo "Running: static-content:deploy" + $(date)
bin/magento setup:static-content:deploy -f
#bin/magento setup:static-content:deploy -f ar_SA

echo "Running: cache:flush" + $(date)
bbin/magento cache:flush
